'hist_Muon0-v1.root':
  type: data
  pretty-name: 'Data'
  group: GData

'hist_Muon0-v2.root':
  type: data
  pretty-name: 'Data'
  group: GData

'hist_Muon1-v1.root':
  type: data
  pretty-name: 'Data'
  group: GData

'hist_Muon1-v2.root':
  type: data
  pretty-name: 'Data'
  group: GData


'hist_TTtoLNu2Q.root':
  type: mc
  pretty-name: 'TTtoLNu2Q'
  cross-section: 202.5
  group: Gttlj
  yields-group: '2\ttbar LJ'
  order: 1

'hist_TTto2L2Nu.root':
  type: mc
  pretty-name: 'TTto2L2Nu'
  cross-section: 97.60
  group: Gttll
  yields-group: '1\ttbar LL'
  order: 2



'hist_WtoLNu-4Jets.root':
  type: mc
  pretty-name: 'WJetsToLNu-4Jets'
  cross-section: 55390
  group: GWJets
  yields-group: 'W+Jets'
  order: 3

