'hist_Muon0-v1.root':
  type: data
  pretty-name: 'Data'
  group: GData

'hist_Muon0-v2.root':
  type: data
  pretty-name: 'Data'
  group: GData

'hist_Muon1-v1.root':
  type: data
  pretty-name: 'Data'
  group: GData

'hist_Muon1-v2.root':
  type: data
  pretty-name: 'Data'
  group: GData

'hist_TTtoLNu2Q.root':
  type: mc
  pretty-name: 'TTtoLNu2Q'
  cross-section: 405.75
  group: Gttlj
  yields-group: '2\ttbar LJ'
  order: 1

'hist_TTto2L2Nu.root':
  type: mc
  pretty-name: 'TTTo2L2Nu'
  cross-section: 98.04
  group: Gttll
  yields-group: '1\ttbar LL'
  order: 2

'hist_TTto4Q.root':
  type: mc
  pretty-name: 'TTto4Q'
  cross-section: 419.82
  group: Gttjj
  yields-group: '3\ttbar Had'
  order: 3

'hist_TBbar_s_4f.root':
  type: mc
  pretty-name: 'SingleTops'
  cross-section: 2.278
  group: GSingleT
  yields-group: '5Single Top'
  order: 8

'hist_TbarB_s.root':
  type: mc
  pretty-name: 'SingleTopt'
  cross-section: 11.43
  group: GSingleT
  yields-group: '5Single Top'
  order: 9

'hist_ST_t_antitop_4f.root':
  type: mc
  pretty-name: 'SingleTbart'
  cross-section: 80.0
  group: GSingleT
  yields-group: '5Single Top'
  order: 10

'hist_ST_tW_top_5f.root':
  type: mc
  pretty-name: 'SingleToptW'
  cross-section: 39.65
  group: GSingleT
  yields-group: '5Single Top'
  order: 11

'hist_ST_tW_antitop_5f.root':
  type: mc
  pretty-name: 'SingleTbartW'
  cross-section: 39.65
  group: GSingleT
  yields-group: '5Single Top'
  order: 12

'hist_ttHto2B.root':
  type: mc
  pretty-name: 'ttHto2B'
  cross-section: 0.5742
  group: GttV
  yields-group: '7tt+X'
  order: 4

'hist_ttHto2C.root':
  type: mc
  pretty-name: 'ttHto2C'
  cross-section: 0.5742
  group: GttV
  yields-group: '7tt+X'
  order: 5

'hist_ttHtoZG.root':
  type: mc
  pretty-name: 'ttHtoZG'
  cross-section: 0.5742
  group: GttV
  yields-group: '7tt+X'
  order: 6

#'hist_TTWJetsToLNu.root':
#  type: mc
#  pretty-name: 'TTWJetsToLNu'
#  cross-section: 0.2163
#  group: GttV
#  yields-group: '7tt+X'
#  order: 16
#
#'hist_TTWJetsToQQ.root':
#  type: mc
#  pretty-name: 'TTWJetsToQQ'
#  cross-section: 0.4432
#  group: GttV
#  yields-group: '7tt+X'
#  order: 17
#
#'hist_TTZToLLNuNu.root':
#  type: mc
#  pretty-name: 'TTZToLLNuNu'
#  cross-section: 0.2439
#  group: GttV
#  yields-group: '7tt+X'
#  order: 18
#
#'hist_TTZToQQ.root':
#  type: mc
#  pretty-name: 'TTZToQQ'
#  cross-section: 0.5113
#  group: GttV
#  yields-group: '7tt+X'
#  order: 19

'hist_WW.root':
  type: mc
  pretty-name: 'WW'
  cross-section: 80.23
  group: GVV
  yields-group: '8VV'
  order: 7

'hist_WZ.root':
  type: mc
  pretty-name: 'WZ'
  cross-section: 29.1
  group: GVV
  yields-group: '8VV'
  order: 8

'hist_ZZ.root':
  type: mc
  pretty-name: 'ZZ'
  cross-section: 13.15
  group: GVV
  yields-group: '8VV'
  order: 9

'hist_DYto2L-2Jets_MLL-10to50.root':
  type: mc
  pretty-name: 'DYJets10to50'
  cross-section: 20950.0
  group: GZJets
  yields-group: '4Z+Jets'
  order: 10

'hist_DYJetsToLL_M50_mg.root':
  type: mc
  pretty-name: 'DYJets'
  cross-section: 5558.0
  group: GZJets
  yields-group: '4Z+Jets'
  order: 11

'hist_DYto2L-2Jets_MLL-50.root':
  type: mc
  pretty-name: 'DYJets'
  cross-section: 6688.0 #140.0 * 1.13
  group: GZJets
  yields-group: '4Z+Jets'
  order: 12

'hist_DYto2L-4Jets_MLL-50.root':
  type: mc
  pretty-name: 'DYJets'
  cross-section: 5467 #139.2 * 1.13
  group: GZJets
  yields-group: '4Z+Jets'
  order: 13

'hist_WtoLNu-4Jets.root':
  type: mc
  pretty-name: 'WtoLNu_4Jets'
  cross-section: 55390
  group: GWJets
  yields-group: '6W+Jets'
  order: 14

#'hist_WJetsToLNu_HT0To100.root':
#  type: mc
#  pretty-name: 'WJetsToLNu_HT0To100'
#  cross-section: 65396.85 # 67350.0 * 0.972
#  scale: 1.0288 # 1/0.972 for generator-event scale, anyway cancels out
#  group: GWJets
#  yields-group: '6W+Jets'
#  order: 25
#  # 65396.85 ~ 65282.37803 = 67350.0 - 1568.7 - 419 - 56.52 - 15.05 - 6.8707 - 1.4488 - 0.03247
#  # generated-events: 72594985 # 74686199 * 0.972 (2016pre)
#  # generated-events: 78691397 # 80958227 * 0.972 (2016post)
#  # generated-events: 76114585 # 78307186 * 0.972 (2017)
#  # generated-events: 78781833 # 81051269 * 0.972 (htcut, 2018)
#
#'hist_WJetsToLNu_HT100To200.root':
#  type: mc
#  pretty-name: 'WJetsToLNu_HT100To200'
#  cross-section: 1568.7 # 1256.0 * 1.249
#  group: GWJets
#  yields-group: '6W+Jets'
#  order: 26
#
#'hist_WJetsToLNu_HT200To400.root':
#  type: mc
#  pretty-name: 'WJetsToLNu_HT200To400'
#  cross-section: 419 # 335.5 * 1.249
#  group: GWJets
#  yields-group: '6W+Jets'
#  order: 27
#
#'hist_WJetsToLNu_HT400To600.root':
#  type: mc
#  pretty-name: 'WJetsToLNu_HT400To600'
#  cross-section: 56.52 # 45.25 * 1.249
#  group: GWJets
#  yields-group: '6W+Jets'
#  order: 28
#
#'hist_WJetsToLNu_HT600To800.root':
#  type: mc
#  pretty-name: 'WJetsToLNu_HT600To800'
#  cross-section: 15.05 # 12.05 * 1.249
#  group: GWJets
#  yields-group: '6W+Jets'
#  order: 29
#
#'hist_WJetsToLNu_HT800To1200.root':
#  type: mc
#  pretty-name: 'WJetsToLNu_HT800To1200'
#  cross-section: 6.8707 # 5.501 * 1.249
#  group: GWJets
#  yields-group: '6W+Jets'
#  order: 30
#
#'hist_WJetsToLNu_HT1200To2500.root':
#  type: mc
#  pretty-name: 'WJetsToLNu_HT1200To2500'
#  cross-section: 1.4488 # 1.16 * 1.249
#  group: GWJets
#  yields-group: '6W+Jets'
#  order: 31
#
#'hist_WJetsToLNu_HT2500ToInf.root':
#  type: mc
#  pretty-name: 'WJetsToLNu_HT2500ToInf'
#  cross-section: 0.03247 # 0.026 * 1.249
#  group: GWJets
#  yields-group: '6W+Jets'
#  order: 32

#'hist_QCD_Pt15To20_MuEnriched.root':
#  type: mc
#  pretty-name: 'QCD'
#  cross-section: 2797000.0
#  group: GQCD
#  yields-group: '9QCD'
#  order: 33

'hist_QCD_Pt20To30_MuEnriched.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 2679000.0
  group: GQCD
  yields-group: '9QCD'
  order: 34

'hist_QCD_Pt30To50_MuEnriched.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 1497000.0
  group: GQCD
  yields-group: '9QCD'
  order: 35

'hist_QCD_Pt50To80_MuEnriched.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 409500.0
  group: GQCD
  yields-group: '9QCD'
  order: 36

'hist_QCD_Pt80To120_MuEnriched.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 95130.0
  group: GQCD
  yields-group: '9QCD'
  order: 37

'hist_QCD_Pt120To170_MuEnriched.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 22980.0
  group: GQCD
  yields-group: '9QCD'
  order: 38

'hist_QCD_Pt170To300_MuEnriched.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 7763
  group: GQCD
  yields-group: '9QCD'
  order: 39

'hist_QCD_Pt300To470_MuEnriched.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 699.1
  group: GQCD
  yields-group: '9QCD'
  order: 40

'hist_QCD_Pt470To600_MuEnriched.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 68.24
  group: GQCD
  yields-group: '9QCD'
  order: 41

'hist_QCD_Pt600To800_MuEnriched.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 21.37
  group: GQCD
  yields-group: '9QCD'
  order: 42

'hist_QCD_Pt800To1000_MuEnriched.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 3.913
  group: GQCD
  yields-group: '9QCD'
  order: 43

'hist_QCD_Pt1000_MuEnriched.root':
  type: mc
  pretty-name: 'QCD'
  cross-section: 1.323
  group: GQCD
  yields-group: '9QCD'
  order: 44
