GData:
  legend: 'Data'
  marker-size: 0.6

Gttll:
  fill-color: '#ee4444'
  legend: 'TTLL'

Gttlj:
  fill-color: '#990000'
  legend: 'TTLJ'

Gttjj:
  fill-color: '#330000'
  legend: 'TTHad'

GttV:
  fill-color: '#ff66ff'
  legend: 'ttV/H'

GZJets:
  fill-color: '#000099'
  legend: 'ZJets'

GWJets:
  fill-color: '#ff9933'
  legend: 'WJets'

GSingleT:
  fill-color: '#990099'
  legend: 'Single t'

GVV:
  fill-color: '#00cccc'
  legend: 'VV'

GQCD:
  fill-color: '#d0cfd4'
  legend: 'QCD'

GFakeTau:
  fill-color: '#ff9933'
  legend: 'Tau MisID'

GLFVSTcs:
  line-color: '#3f90da'
  legend: 'ST LFV^{tc#mu#tau}_{Scalar}'

GLFVSTcv:
  line-color: '#3f90da'
  legend: 'ST LFV^{tc#mu#tau}_{Vector}'

GLFVSTct:
  line-color: '#3f90da'
  legend: 'ST LFV^{tc#mu#tau}_{Tensor}'

GLFVSTus:
  line-color: '#a96b59'
  legend: 'ST LFV^{tu#mu#tau}_{Scalar}'

GLFVSTuv:
  line-color: '#a96b59'
  legend: 'ST LFV^{tu#mu#tau}_{Vector}'

GLFVSTut:
  line-color: '#a96b59'
  legend: 'ST LFV^{tu#mu#tau}_{Tensor}'

GLFVTTcs:
  line-color: '#92dadd'
  legend: 'TT LFV^{tc#mu#tau}_{Scalar}'

GLFVTTcv:
  line-color: '#92dadd'
  legend: 'TT LFV^{tc#mu#tau}_{Vector}'

GLFVTTct:
  line-color: '#92dadd'
  legend: 'TT LFV^{tc#mu#tau}_{Tensor}'

GLFVTTus:
  line-color: '#ffa90e'
  legend: 'TT LFV^{tu#mu#tau}_{Scalar}'

GLFVTTuv:
  line-color: '#ffa90e'
  legend: 'TT LFV^{tu#mu#tau}_{Vector}'

GLFVTTut:
  line-color: '#ffa90e'
  legend: 'TT LFV^{tu#mu#tau}_{Tensor}'

#############
#  postfit  #
#############

Gtt:
  fill-color: '#ee4444'
  legend: 't#bar{t}'

# resue ST colors
GLFVcs:
  line-color: '#3f90da'
  legend: 'LFV^{tc#mu#tau}_{Scalar}'

GLFVcv:
  line-color: '#3f90da'
  legend: 'LFV^{tc#mu#tau}_{Vector}'

GLFVct:
  line-color: '#3f90da'
  legend: 'LFV^{tc#mu#tau}_{Tensor}'

GLFVus:
  line-color: '#a96b59'
  legend: 'LFV^{tu#mu#tau}_{Scalar}'

GLFVuv:
  line-color: '#a96b59'
  legend: 'LFV^{tu#mu#tau}_{Vector}'

GLFVut:
  line-color: '#a96b59'
  legend: 'LFV^{tu#mu#tau}_{Tensor}'

#As we never show QCD, reuse color
# -> use gray for misID, WJet color for other if needed
Gother:
  fill-color: '#d0cfd4'
  legend: 'Other'
