configuration:
  width: 450
  height: 450
  luminosity-label: '%1$.0f fb^{-1} (13 TeV)'
  experiment: " CMS"
  experiment-label-paper: true
  extra-label: " WIP"
  root: ''
  luminosity: 61897.1
  luminosity-error: 0.016
  error-fill-style: 3254
  error-fill-color: "#ee556270"
  staterror-fill-style: 3145
  staterror-fill-color: 7
  ratio-fit-error-fill-style: 1001
  ratio-fit-error-fill-color: "#aa556270"
  ratio-fit-line-color: "#0B486B"
  blinded-range-fill-color: "#29556270"
  blinded-range-fill-style: 1001
  yields-table-align: v
  book-keeping-file: 'plots.root'
  yields-table-numerical-precision-yields: 1
  generated-events-histogram: 'hcounter'
  generated-events-bin: 2

files: 
  include: ['files_Run3.yml']

legend:
  #position: [0.18, 0.70, 0.96, 0.88]
  #position: [0.36, 0.70, 0.94, 0.88]
  #position: [0.35, 0.66, 0.93, 0.88] #org
  position: [0.42, 0.45, 0.90, 0.88]
  columns: 3
  #columns: 2

groups:
  include: ['groups.yml']
  #include: ['groups_merged.yml']

systematics:

plots:
  include: ['histos.yml']
