#muon multiplicities
'h_nmuonpass_notausf_S1':
  y-axis-format: "%1% / bin"
  log-y: true 
  sort-by-yields: true 
  save-extensions: ['pdf', 'png']

'h_nmuonpass_S1':
  y-axis-format: "%1% / bin"
  log-y: true 
  sort-by-yields: true 
  save-extensions: ['pdf', 'png']

'h_nmuonpass_S2':
  y-axis-format: "%1% / bin"
  log-y: true 
  sort-by-yields: true 
  save-extensions: ['pdf', 'png']

'h_nmuonpass_S3':
  y-axis-format: "%1% / bin"
  log-y: true 
  sort-by-yields: true 
  save-extensions: ['pdf', 'png']

'h_nmuonpass_S4':
  y-axis-format: "%1% / bin"
  log-y: true 
  sort-by-yields: true 
  save-extensions: ['pdf', 'png']

'h_nmuonpass_S5':
  y-axis-format: "%1% / bin"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf', 'png']

#tau multiplicities
'h_ncleantaupass_notausf_S1':
  y-axis-format: "%1% / bin"
  log-y: true 
  sort-by-yields: true 
  save-extensions: ['pdf', 'png']

'h_ncleantaupass_S1':
  y-axis-format: "%1% / bin"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf', 'png']

'h_ncleantaupass_S2':
  y-axis-format: "%1% / bin"
  log-y: true 
  sort-by-yields: true 
  save-extensions: ['pdf', 'png']

'h_ncleantaupass_S3':
  y-axis-format: "%1% / bin"
  log-y: true 
  sort-by-yields: true 
  save-extensions: ['pdf', 'png']

'h_ncleantaupass_S4':
  y-axis-format: "%1% / bin"
  log-y: true 
  sort-by-yields: true 
  save-extensions: ['pdf', 'png']

'h_ncleantaupass_S5':
  y-axis-format: "%1% / bin"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf', 'png']

#jet multiplicities
'h_ncleanjetspass_notausf_S1':
  y-axis-format: "%1% / bin"
  log-y: true 
  sort-by-yields: true 
  save-extensions: ['pdf', 'png']

'h_ncleanjetspass_S1':
  y-axis-format: "%1% / bin"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf', 'png']

'h_ncleanjetspass_S2':
  y-axis-format: "%1% / bin"
  log-y: true 
  sort-by-yields: true 
  save-extensions: ['pdf', 'png']

'h_ncleanjetspass_S3':
  y-axis-format: "%1% / bin"
  log-y: true 
  sort-by-yields: true 
  save-extensions: ['pdf', 'png']

'h_ncleanjetspass_S4':
  y-axis-format: "%1% / bin"
  log-y: true 
  sort-by-yields: true 
  save-extensions: ['pdf', 'png']

'h_ncleanjetspass_S5':
  y-axis-format: "%1% / bin"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf', 'png']

#b jet multiplicities
'h_ncleanbjetspass_notausf_S1':
  y-axis-format: "%1% / bin"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf', 'png']

'h_ncleanbjetspass_S1':
  y-axis-format: "%1% / bin"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf', 'png']

'h_ncleanbjetspass_S2':
  y-axis-format: "%1% / bin"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf', 'png']

'h_ncleanbjetspass_S3':
  y-axis-format: "%1% / bin"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf', 'png']

'h_ncleanbjetspass_S4':
  y-axis-format: "%1% / bin"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf', 'png']

'h_ncleanbjetspass_S5':
  y-axis-format: "%1% / bin"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf', 'png']

#PV
'h_nvtx_notausf_S1':
  y-axis-format: "%1% / bin"
  save-extensions: ['pdf', 'png']

'h_nvtx_S1':
  y-axis-format: "%1% / bin"
  save-extensions: ['pdf', 'png']

'h_nvtx_S2':
  y-axis-format: "%1% / bin"
  save-extensions: ['pdf', 'png']

'h_nvtx_S3':
  y-axis-format: "%1% / bin"
  save-extensions: ['pdf', 'png']

'h_nvtx_S4':
  y-axis-format: "%1% / bin"
  save-extensions: ['pdf', 'png']

'h_nvtx_S5':
  y-axis-format: "%1% / bin"
  save-extensions: ['pdf', 'png']

#PuppiMET pt
'h_puppimet_pt_notausf_S1':
  save-extensions: ['pdf', 'png']

'h_puppimet_pt_S1':
  save-extensions: ['pdf', 'png']

'h_puppimet_pt_S2':
  save-extensions: ['pdf', 'png']

'h_puppimet_pt_S3':
  save-extensions: ['pdf', 'png']

'h_puppimet_pt_S4':
  save-extensions: ['pdf', 'png']

'h_puppimet_pt_S5':
  save-extensions: ['pdf', 'png']

#PuppiMET phi
'h_puppimet_phi_notausf_S1':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_puppimet_phi_S1':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_puppimet_phi_S2':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_puppimet_phi_S3':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_puppimet_phi_S4':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_puppimet_phi_S5':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

#PuppiMET sumEt
'h_puppisum_et_notausf_S1':
  save-extensions: ['pdf', 'png']

'h_puppisum_et_S1':
  save-extensions: ['pdf', 'png']

'h_puppisum_et_S2':
  save-extensions: ['pdf', 'png']

'h_puppisum_et_S3':
  save-extensions: ['pdf', 'png']

'h_puppisum_et_S4':
  save-extensions: ['pdf', 'png']

'h_puppisum_et_S5':
  save-extensions: ['pdf', 'png']

#Muon pt
'h_muon1_pt_notausf_S1':
  save-extensions: ['pdf','png']

'h_muon1_pt_S1':
  save-extensions: ['pdf','png']

'h_muon1_pt_S2':
  save-extensions: ['pdf','png']

'h_muon1_pt_S3':
  save-extensions: ['pdf','png']

'h_muon1_pt_S4':
  save-extensions: ['pdf','png']

'h_muon1_pt_S5':
  save-extensions: ['pdf','png']

#Muon eta
'h_muon1_eta_notausf_S1':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_muon1_eta_S1':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_muon1_eta_S2':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_muon1_eta_S3':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_muon1_eta_S4':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_muon1_eta_S5':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

#Lepton + MET MT
'h_lepMET_mt_notausf_S1':
  save-extensions: ['pdf', 'png']

'h_lepMET_mt_S1':
  save-extensions: ['pdf', 'png']

'h_lepMET_mt_S2':
  save-extensions: ['pdf', 'png']

'h_lepMET_mt_S3':
  save-extensions: ['pdf', 'png']

'h_lepMET_mt_S4':
  save-extensions: ['pdf', 'png']

'h_lepMET_mt_S5':
  save-extensions: ['pdf', 'png']

#tau pt
'h_tau1_pt_S2':
  save-extensions: ['pdf', 'png']

'h_tau1_pt_S3':
  save-extensions: ['pdf', 'png']

'h_tau1_pt_S4':
  save-extensions: ['pdf', 'png']

'h_tau1_pt_S5':
  save-extensions: ['pdf', 'png']

#tau eta
'h_tau1_eta_S2':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_tau1_eta_S3':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_tau1_eta_S4':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_tau1_eta_S5':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

#tau mass
'h_tau1_mass_S2':
  save-extensions: ['pdf', 'png']

'h_tau1_mass_S3':
  save-extensions: ['pdf', 'png']

'h_tau1_mass_S4':
  save-extensions: ['pdf', 'png']

'h_tau1_mass_S5':
  save-extensions: ['pdf', 'png']

#tau decayMode
'h_tau1_decayMode_S2':
  y-axis-format: "%1% / bin"
  save-extensions: ['pdf', 'png']

'h_tau1_decayMode_S3':
  y-axis-format: "%1% / bin"
  save-extensions: ['pdf', 'png']

'h_tau1_decayMode_S4':
  y-axis-format: "%1% / bin"
  save-extensions: ['pdf', 'png']

'h_tau1_decayMode_S5':
  y-axis-format: "%1% / bin"
  save-extensions: ['pdf', 'png']

#Lepton + tau system variables
'h_leptau_dEta_S2':
  x-axis: "\\Delta\\eta(\\mu, \\tau_{h})"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_leptau_dEta_S3':
  x-axis: "\\Delta\\eta(\\mu, \\tau_{h})"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_leptau_dEta_S4':
  x-axis: "\\Delta\\eta(\\mu, \\tau_{h})"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_leptau_dEta_S5':
  x-axis: "\\Delta\\eta(\\mu, \\tau_{h})"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_leptau_dPhi_S2':
  x-axis: "\\Delta\\phi(\\mu, \\tau_{h})"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_leptau_dPhi_S3':
  x-axis: "\\Delta\\phi(\\mu, \\tau_{h})"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_leptau_dPhi_S4':
  x-axis: "\\Delta\\phi(\\mu, \\tau_{h})"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_leptau_dPhi_S5':
  x-axis: "\\Delta\\phi(\\mu, \\tau_{h})"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_leptau_dR_S2':
  x-axis: "\\Delta R(\\mu, \\tau_{h})"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_leptau_dR_S3':
  x-axis: "\\Delta R(\\mu, \\tau_{h})"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_leptau_dR_S4':
  x-axis: "\\Delta R(\\mu, \\tau_{h})"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_leptau_dR_S5':
  x-axis: "\\Delta R(\\mu, \\tau_{h})"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

#Muon tau mass
'h_leptau_mass_S2':
  x-axis: "Mass of \\mu + \\tau_{h} (GeV)"
  save-extensions: ['pdf', 'png']

'h_leptau_mass_S3':
  x-axis: "Mass of \\mu + \\tau_{h} (GeV)"
  save-extensions: ['pdf', 'png']

'h_leptau_mass_S4':
  x-axis: "Mass of \\mu + \\tau_{h} (GeV)"
  save-extensions: ['pdf', 'png']

'h_leptau_mass_S5':
  x-axis: "Mass of \\mu + \\tau_{h} (GeV)"
  save-extensions: ['pdf', 'png']

'h_leptau_mass_blind_S2':
  x-axis: "Mass of \\mu + \\tau_{h} (GeV)"
  blinded-range: [100, 200]
  save-extensions: ['pdf', 'png']

'h_leptau_mass_blind_S3':
  x-axis: "Mass of \\mu + \\tau_{h} (GeV)"
  blinded-range: [100, 200]
  save-extensions: ['pdf', 'png']

'h_leptau_mass_blind_S4':
  x-axis: "Mass of \\mu + \\tau_{h} (GeV)"
  blinded-range: [100, 200]
  save-extensions: ['pdf', 'png']

'h_leptau_mass_blind_S5':
  x-axis: "Mass of \\mu + \\tau_{h} (GeV)"
  blinded-range: [100, 200]
  save-extensions: ['pdf', 'png']

#jet ht
'h_jet_ht_notausf_S1':
  rebin: 2
  save-extensions: ['pdf', 'png']

'h_jet_ht_S1':
  rebin: 2
  save-extensions: ['pdf', 'png']

'h_jet_ht_S2':
  rebin: 2
  save-extensions: ['pdf', 'png']

'h_jet_ht_S3':
  rebin: 2
  save-extensions: ['pdf', 'png']

'h_jet_ht_S4':
  rebin: 2
  save-extensions: ['pdf', 'png']

'h_jet_ht_S5':
  rebin: 2
  save-extensions: ['pdf', 'png']

#jet1 pt
'h_jet1_pt_notausf_S1':
  save-extensions: ['pdf', 'png']

'h_jet1_pt_S1':
  save-extensions: ['pdf', 'png']

'h_jet1_pt_S2':
  save-extensions: ['pdf', 'png']

'h_jet1_pt_S3':
  save-extensions: ['pdf', 'png']

'h_jet1_pt_S4':
  save-extensions: ['pdf', 'png']

'h_jet1_pt_S5':
  save-extensions: ['pdf', 'png']

#jet1 eta
'h_jet1_eta_notausf_S1':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_jet1_eta_S1':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_jet1_eta_S2':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_jet1_eta_S3':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_jet1_eta_S4':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_jet1_eta_S5':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

#jet1 mass
'h_jet1_mass_notausf_S1':
  save-extensions: ['pdf', 'png']

'h_jet1_mass_S1':
  save-extensions: ['pdf', 'png']

'h_jet1_mass_S2':
  save-extensions: ['pdf', 'png']

'h_jet1_mass_S3':
  save-extensions: ['pdf', 'png']

'h_jet1_mass_S4':
  save-extensions: ['pdf', 'png']

'h_jet1_mass_S5':
  save-extensions: ['pdf', 'png']

#jet1 btag
'h_jet1_btag_notausf_S1':
  y-axis-format: "%1% / %2$.2f units"
  save-extensions: ['pdf', 'png']

'h_jet1_btag_S1':
  y-axis-format: "%1% / %2$.2f units"
  save-extensions: ['pdf', 'png']

'h_jet1_btag_S2':
  y-axis-format: "%1% / %2$.2f units"
  save-extensions: ['pdf', 'png']

'h_jet1_btag_S3':
  y-axis-format: "%1% / %2$.2f units"
  save-extensions: ['pdf', 'png']

'h_jet1_btag_S4':
  y-axis-format: "%1% / %2$.2f units"
  save-extensions: ['pdf', 'png']

'h_jet1_btag_S5':
  y-axis-format: "%1% / %2$.2f units"
  save-extensions: ['pdf', 'png']

#jet2 pt
'h_jet2_pt_S4':
  save-extensions: ['pdf', 'png']

'h_jet2_pt_S5':
  save-extensions: ['pdf', 'png']

#jet2 eta
'h_jet2_eta_S4':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_jet2_eta_S5':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

#jet2 mass
'h_jet2_mass_S4':
  save-extensions: ['pdf', 'png']

'h_jet2_mass_S5':
  save-extensions: ['pdf', 'png']

#jet2 btag
'h_jet2_btag_S4':
  y-axis-format: "%1% / %2$.2f units"
  save-extensions: ['pdf', 'png']

'h_jet2_btag_S5':
  y-axis-format: "%1% / %2$.2f units"
  save-extensions: ['pdf', 'png']

#jet3 pt
'h_jet3_pt_S4':
  save-extensions: ['pdf', 'png']

'h_jet3_pt_S5':
  save-extensions: ['pdf', 'png']

#jet3 eta
'h_jet3_eta_S4':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_jet3_eta_S5':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

#jet3 mass
'h_jet3_mass_S4':
  save-extensions: ['pdf', 'png']

'h_jet3_mass_S5':
  save-extensions: ['pdf', 'png']

#jet3 btag
'h_jet3_btag_S4':
  y-axis-format: "%1% / %2$.2f units"
  save-extensions: ['pdf', 'png']

'h_jet3_btag_S5':
  y-axis-format: "%1% / %2$.2f units"
  save-extensions: ['pdf', 'png']

#bjet at step5
'h_bjet1_pt_S5':
  save-extensions: ['pdf', 'png']

'h_bjet1_eta_S5':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_bjet1_mass_S5':
  save-extensions: ['pdf', 'png']

'h_bjet1_btag_S5':
  y-axis-format: "%1% / %2$.2f units"
  save-extensions: ['pdf', 'png']

#st_met
'h_st_met_S4':
  rebin: 2
  save-extensions: ['pdf', 'png']

'h_st_met_S5':
  rebin: 2
  save-extensions: ['pdf', 'png']

'h_st_met_binwidth_S4':
  y-axis: "Events / GeV"
  y-axis-format: "%1%"
  scale-option: "WIDTH"
  rebin: 2
  log-y: true
  log-y-axis-range: [0.02, 200]
  save-extensions: ['pdf', 'png']

'h_st_met_binwidth_S5':
  y-axis: "Events / GeV"
  y-axis-format: "%1%"
  scale-option: "WIDTH"
  rebin: 2
  log-y: true
  log-y-axis-range: [0.02, 110]
  save-extensions: ['pdf', 'png']

#DNN Kinematic & Topology Variables
'h_lepmet_dPhi_notausf_S1':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_lepmet_dPhi_S2':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_lepmet_dPhi_S3':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_lepmet_dPhi_S4':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_lepmet_dPhi_S5':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_taumet_dPhi_S2':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_taumet_dPhi_S3':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_taumet_dPhi_S4':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_taumet_dPhi_S5':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_lepbjet_dR_S5':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_taubjet_dR_S5':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_lfv_top_mass_S5':
  x-axis: "m(\\mu + \\tau_{h} + b) (GeV)"
  save-extensions: ['pdf', 'png']

#Top Mass Reconstruction Variables (chi2)
'h_chi2_S5':
  x-axis-range: [0, 950]
  y-axis-format: "%1% / %2$.0f"
  blinded-range: [1, 49]
  save-extensions: ['pdf', 'png']

'h_chi2_SMTop_mass_S5':
  x-axis: 'm_{t}^{hadronic} (GeV)'
  blinded-range: [100, 250]
  save-extensions: ['pdf', 'png']

'h_chi2_SMTop_pt_S5':
  x-axis: 't_{hadronic} p_{T} (GeV)'
  blinded-range: [300, 399]
  save-extensions: ['pdf', 'png']

'h_chi2_SMTop_pt_notoppt_S5':
  x-axis: 't_{hadronic} p_{T} (GeV)'
  blinded-range: [300, 399]
  save-extensions: ['pdf', 'png']

'h_chi2_SMW_mass_S5':
  x-axis: 'm_{W}^{hadronic} (GeV)'
  blinded-range: [30, 130]
  save-extensions: ['pdf', 'png']

'h_chi2_wqq_dEta_S5':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_chi2_wqq_dPhi_S5':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']

'h_chi2_wqq_dR_S5':
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf', 'png']
